<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 9/17/18
 * Time: 2:13 PM
 */

namespace execut\shops\models;

use execut\crudFields\Behavior;
use execut\crudFields\BehaviorStub;
use execut\crudFields\fields\Id;
use execut\crudFields\fields\Image;
use execut\crudFields\fields\NumberField;
use execut\crudFields\ModelsHelperTrait;
use Imagine\Image\ImageInterface;
use yii\db\ActiveRecord;
class Shop extends ActiveRecord
{
    use BehaviorStub, ModelsHelperTrait;
    const MODEL_NAME = '{n,plural,=0{Shop} =1{Shop} other{Shops}}';
    public $imageFile = null;
    public $schemaFile = null;
    public function behaviors()
    {
        return [
            'fields' => [
                'class' => Behavior::class,
                'fields' => $this->getStandardFields(null, [
                    'address' => [
                        'required' => true,
                        'attribute' => 'address',
                    ],
                    'short_address' => [
                        'required' => true,
                        'attribute' => 'short_address',
                    ],
                    'phone_1' => [
                        'attribute' => 'phone_1',
                    ],
                    'phone_2' => [
                        'attribute' => 'phone_2',
                    ],
                    'work_time' => [
                        'attribute' => 'work_time',
                    ],
                    'coords' => [
                        'attribute' => 'coords',
                        'rules' => [
                            [
                                'coords',
                                'match',
                                'pattern' => '/^\d\d\.\d\d\d\d\d\d\d?\d?, \d\d\.\d\d\d\d\d\d\d?\d?$/',
                            ]
                        ],
                    ],
                    'specialization' => [
                        'attribute' => 'specialization',
                    ],
                    'text_header_map' => [
                        'attribute' => 'text_header_map',
                    ],
                    'sort' => [
                        'class' => NumberField::class,
                        'attribute' => 'sort',
                    ],
                    'schemaFile' => [
                        'class' => Image::class,
                        'attribute' => 'schemaFile',
                        'sizes' => [
                            'schema_201' => [
                                'width' => 201,
                                'height' => 165,
                                'mode' => ImageInterface::THUMBNAIL_OUTBOUND,
                            ],
                        ],
                        'dataAttribute' => 'schema',
                        'previewRoute' => '/shops/shops/schema',
                        'fileNameAttribute' => 'schema_name',
                        'previewDataAttribute' => 'schema_201',
                        'fileExtensionAttribute' => 'schema_extension',
                        'md5Attribute' => 'schema_md5',
                        'fileMimeTypeAttribute' => false,
                    ],
                    'imageFile' => [
                        'class' => Image::class,
                        'attribute' => 'imageFile',
                        'sizes' => [
                            'image_201' => [
                                'width' => 201,
                                'height' => 165,
                                'mode' => ImageInterface::THUMBNAIL_OUTBOUND,
                            ],
                        ],
                        'dataAttribute' => 'image',
                        'previewRoute' => '/shops/shops/image',
                        'fileNameAttribute' => 'image_name',
                        'previewDataAttribute' => 'image_201',
                        'fileExtensionAttribute' => 'image_extension',
                        'md5Attribute' => 'image_md5',
                        'fileMimeTypeAttribute' => false,
                    ],
                ]),
                'plugins' => \yii::$app->getModule('shops')->getShopsFieldsPlugins(),
            ],
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    public static function find()
    {
        return new \execut\shops\models\queries\Shop(self::class);
    }

    public function __toString() {
        return '#' . $this->id;
    }

    public static function tableName()
    {
        return 'shops_shops';
    }

    public function getUrl() {
        return ['/shops/shops/view', 'id' => $this->id];
    }

    public function getImageUrl($dataAttribute = 'image_201') {
        if (empty($this->image_md5)) {
            return;
        }

        return [
            '/shops/shops/image',
            'id' => $this->id,
            'dataAttribute' => $dataAttribute,
            'extension' => $this->image_extension,
        ];
    }

    public function getSchemaUrl($dataAttribute = 'schema_201') {
        if (empty($this->schema_md5)) {
            return;
        }

        return [
            '/shops/shops/schema',
            'id' => $this->id,
            'dataAttribute' => $dataAttribute,
            'extension' => $this->schema_extension,
        ];
    }

    public function getLastTime() {
        if ($this->updated) {
            return $this->updated;
        }

        return $this->created;
    }
}